title = "DiscoTupperBot"

# Logging settings
[logging]
file_path = 'logs/bot.log'
level = "INFO"
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> [<bold>{level.icon}<level>{level}</level></bold>] <magenta>{name}</magenta> - {message}"
rotation = "1 day"
enqueue = "True"
colorize = "True"

[bot]
initial_extensions = ['roll', 'tuppers_message', 'tuppers_manage_commands', 'users', 'tuppers_extra_commands']
prefixes = [".", "/"]
admin_roles = ['test_admin_role']
player_roles = ['test_player_role']
reaction_to_edit = "📝"
reaction_to_remove = "❌"
language = "en"
log_channel_id = 1248345323357601853
random_source = "pyrandom" # pyrandom

[actor]
default_avatar_url = "https://chrono-edge.taruu.ru/images/c/c9/Logo.png"
